id = "penumbra-plus"
name = "Penumbra+"
version = "0.0.4"
schema_version = 1
authors = ["everdrone"]
description = "Zed port of Helix penumbra+"
repository = "https://github.com/everdrone/zed-penumbra-plus"
